server:
  port: 8078
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/security?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid参数调优（可选）,若配置如下参数则必须手动添加配置类
    # 初始化大小，最小，最大
    # 配置获取连接等待超时的时间
    druid:
      min-idle: 5
      max-active: 20
      initial-size: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
mybatis:
  mapper-locations: classpath*:mapper/*.xml




##数据库连接中修改数据源类型
#  spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#  spring.datasource.timeBetweenEvictionRunsMillis=60000
#  # 配置一个连接在池中最小生存的时间，单位是毫秒
#  spring.datasource.minEvictableIdleTimeMillis=300000
#  # 测试连接
#  spring.datasource.testWhileIdle=true
#  spring.datasource.testOnBorrow=false
#  spring.datasource.testOnReturn=false
#  # 打开PSCache，并且指定每个连接上PSCache的大小
#  spring.datasource.poolPreparedStatements=true
#  # 配置监控统计拦截的filters
#  # asyncInit是1.1.4中新增加的配置，如果有initialSize数量较多时，打开会加快应用启动时间
#  spring.datasource.asyncInit=true
#  # druid监控配置信息
#  spring.datasource.filters=stat,config
#  spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
#  spring.datasource.useGlobalDataSourceStat=true
#  spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
